AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - '**/application.rb'
    - '**/Rakefile'
  Exclude:
    # You could specify set of files or dirs while you want to be ignored by rubocop
    - 'vendor/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'Gemfile'
    - 'Gemfile.lock'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'config/add_vagrant_config.rb'
    - 'puppet/**/*'

Rails:
  Enabled: true

Rails/Blank:
  Exclude: # Rubocop 0.48.0 bug. Already fixed in master. Remove after 0.48.0
    - 'config/initializers/doorkeeper.rb'
    - 'lib/auto_complete_username.rb'
    - 'lib/authorization.rb'
    - 'app/helpers/actions_helper.rb'
    - 'app/models/reviewer_batch.rb'
    - 'app/models/conference.rb'
    - 'app/models/recommendation.rb'
    - 'app/models/session_type.rb'
    - 'app/models/session.rb'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - 'spec/factories.rb'
    - 'spec/factories/**/*.rb'
    - 'Guardfile'
    - 'Vagrantfile'

Style/Documentation:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false # Can only be enabled once we're on Rails 5

Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate/**/*.rb'

Rails/OutputSafety:
  Enabled: false # Having weird errors with safe_join

Style/FileName:
  Exclude:
    - 'Guardfile'
    - 'Vagrantfile'
    - 'Procfile'
    - 'puppet/Puppetfile'
