language: ruby
rvm:
  - 2.4.3
before_install:
  - gem update --system
before_script:
  - cp ./config/config.{example,yml}
  - cp ./config/database.{example,yml}
script:
  - RAILS_ENV=test bundle exec rake db:drop db:create db:schema:load
  - RAILS_ENV=test bundle exec rake ci
bundler_args: --without development production
