language: ruby
rvm:
  - 2.3.3
before_script:
  - cp ./config/config.{example,yml}
  - cp ./config/database.{travis,yml}
script:
  - RAILS_ENV=test bundle exec rake db:drop db:create db:migrate
  - RAILS_ENV=test bundle exec rake ci
bundler_args: --without development production
